# -*- coding: utf-8 -*-
"""TesteBaseline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hH0zWyj5C_SID8uillwaJ6luyQ5ol97t
"""

!pip install optuna

import yfinance as yf
import pandas as pd
import numpy as np
import lightgbm as lgb
import optuna
from sklearn.metrics import mean_squared_error, mean_absolute_percentage_error
from sklearn.model_selection import TimeSeriesSplit
import matplotlib.pyplot as plt
from datetime import datetime
import warnings
import joblib

warnings.filterwarnings('ignore')

# 1. CONFIGURAÇÕES INICIAIS
TICKER = 'PETR4.SA'
WINDOW = 21 # Janela de volatilidade
START_DATE = '2018-01-01'

#Data de "Hoje"
#END_DATE = datetime.today().strftime('%Y-%m-%d')
#Data teste
END_DATE = '2026-04-01'

def fetch_and_prepare_data(ticker):
    print(f"Baixando dados reais de {ticker} até {END_DATE}...")
    # auto_adjust=True já traz os preços ajustados por dividendos e desdobramentos
    df = yf.download(ticker, start=START_DATE, end=END_DATE, auto_adjust=True, progress=False)

    if isinstance(df.columns, pd.MultiIndex):
        df.columns = df.columns.get_level_values(0)

    # ENGENHARIA DE DADOS

    # 1. Retornos Logarítmicos: Padrão quantitativo (simétrico e somável)
    df['returns'] = np.log(df['Close'] / df['Close'].shift(1))

    # 2. A Volatilidade Atual (Target do dia): Desvio padrão anualizado
    df['target_vol'] = df['returns'].rolling(window=WINDOW).std() * np.sqrt(252)

    # 3. O ALVO DO FUTURO:
    # Puxamos a volatilidade de 5 dias no futuro para a linha de hoje.
    # É isso que ensina a máquina a prever a semana que vem!
    df['target_vol_future'] = df['target_vol'].shift(-5)

    # CRIAÇÃO DAS FEATURES

    # Memória de curto prazo
    df['lag_vol_1'] = df['target_vol'].shift(1)
    df['lag_vol_5'] = df['target_vol'].shift(5)
    df['returns_sq'] = df['returns']**2
    df['ema_returns'] = df['returns'].ewm(span=WINDOW).mean()

    # Volatilidade de Parkinson (A oscilação Intraday / Pânico do dia)
    # Usa a Máxima e a Mínima do dia.
    rs = (1.0 / (4.0 * np.log(2.0))) * (np.log(df['High'] / df['Low']) ** 2)
    df['parkinson_vol'] = np.sqrt(rs.rolling(window=WINDOW).mean()) * np.sqrt(252)

    # Médias Móveis da Volatilidade (Tendências de curto, médio e longo prazo)
    df['vol_media_5d'] = df['target_vol'].rolling(window=5).mean()
    df['vol_media_21d'] = df['target_vol'].rolling(window=21).mean()
    df['vol_media_63d'] = df['target_vol'].rolling(window=63).mean()

    # Momentos Estatísticos (A forma como o mercado está se comportando)
    df['skew_21'] = df['returns'].rolling(window=WINDOW).skew() # Assimetria (viés de alta/baixa)
    df['kurt_21'] = df['returns'].rolling(window=WINDOW).kurt() # Curtose (risco de eventos extremos/cisnes negros)

    # Limpeza: Removemos dias que não têm features calculadas (início da série)
    df_features_prontas = df.dropna(subset=['lag_vol_1', 'parkinson_vol', 'kurt_21'])
    return df_features_prontas

# 2. PREPARAÇÃO DE TREINO, TESTE E O "FUTURO DESCONHECIDO"

df_model = fetch_and_prepare_data(TICKER)

features = [
    'lag_vol_1', 'lag_vol_5', 'returns_sq', 'ema_returns',
    'parkinson_vol', 'vol_media_5d', 'vol_media_21d',
    'vol_media_63d', 'skew_21', 'kurt_21'
]

# Separamos os dados em duas caixas:
# 1. Histórico: Onde temos o target do futuro preenchido (dá pra treinar/testar)
df_historico = df_model.dropna(subset=['target_vol_future'])

# 2. O Futuro Real: Os últimos 5 dias do dataset. Eles têm features, mas o
# 'target_vol_future' é NaN (porque o futuro ainda não aconteceu!).
df_futuro_real = df_model[df_model['target_vol_future'].isna()]

X = df_historico[features]
y = df_historico['target_vol_future']

# Divisão de 80% Treino / 20% Teste (sem embaralhar, respeitando a linha do tempo)
split_idx = int(len(df_historico) * 0.8)
X_train, X_test = X.iloc[:split_idx], X.iloc[split_idx:]
y_train, y_test = y.iloc[:split_idx], y.iloc[split_idx:]

print(f"\nDados separados! Treino: {len(X_train)} dias | Teste: {len(X_test)} dias.")

# 3. OTIMIZAÇÃO COM OPTUNA E TIMESERIESSPLIT
def objective(trial):
    param = {
        'objective': 'regression',
        'metric': 'rmse',
        'verbosity': -1,
        'boosting_type': 'gbdt',
        'learning_rate': trial.suggest_float('learning_rate', 1e-3, 0.1, log=True),
        'num_leaves': trial.suggest_int('num_leaves', 2, 64),
        'feature_fraction': trial.suggest_float('feature_fraction', 0.4, 1.0),
        'bagging_fraction': trial.suggest_float('bagging_fraction', 0.4, 1.0),
        'bagging_freq': trial.suggest_int('bagging_freq', 1, 7),
        'min_child_samples': trial.suggest_int('min_child_samples', 5, 100),
    }

    tscv = TimeSeriesSplit(n_splits=5)
    errors = []

    for train_index, val_index in tscv.split(X_train):
        X_t, X_v = X_train.iloc[train_index], X_train.iloc[val_index]
        y_t, y_v = y_train.iloc[train_index], y_train.iloc[val_index]

        gbm = lgb.LGBMRegressor(**param)

        # O early_stopping avisa a hora certa de parar para não decorar os dados (Overfitting)
        callbacks = [lgb.early_stopping(stopping_rounds=30, verbose=False)]
        gbm.fit(X_t, y_t, eval_set=[(X_v, y_v)], callbacks=callbacks)

        preds = gbm.predict(X_v)
        errors.append(np.sqrt(mean_squared_error(y_v, preds)))

    return np.mean(errors)

# Executa a busca pelos melhores parâmetros (reduzido para 20 pra rodar rápido ao vivo)
optuna.logging.set_verbosity(optuna.logging.WARNING)
print("Otimizando hiperparâmetros do modelo (Isso leva alguns segundos)...")
study = optuna.create_study(direction='minimize')
study.optimize(objective, n_trials=20)

# 4. TREINO FINAL E TRAVAS DE SEGURANÇA (O Clip)

best_params = study.best_params
model = lgb.LGBMRegressor(**best_params)
model.fit(X_train, y_train)

# Calculamos o limite máximo (Percentil 97) histórico para não prever "fim do mundo"
limite_maximo_vol = np.percentile(y_train, 97)

# 5. AVALIAÇÃO DO MODELO NO PASSADO RECENTE (O Backtest)

test_preds = model.predict(X_test)
# Trava as previsões dentro de limites realistas (1% no mínimo, Cap no máximo)
test_preds = np.clip(test_preds, 0.01, limite_maximo_vol)

final_rmse = np.sqrt(mean_squared_error(y_test, test_preds))
final_mape = mean_absolute_percentage_error(y_test, test_preds)

# Baseline: Prever que o futuro será igual à média dos últimos 5 dias
baseline_preds = X_test['vol_media_5d'].values
baseline_rmse = np.sqrt(mean_squared_error(y_test, baseline_preds))

print(f"\n===============================================")
print(f"RESULTADO DO BACKTEST (Set de Teste)")
print(f"===============================================")
print(f"  RMSE : {final_rmse:.5f} (Margem de erro)")
print(f"  RMSE Baseline : {baseline_rmse:.5f} (Erro da média móvel)")
print(f"  MAPE : {final_mape*100:.2f}% (Erro percentual médio)")

# 6. A PREVISÃO DO FUTURO

# Pegamos a última linha válida do mercado
ultima_linha = df_futuro_real.tail(1)
data_base = ultima_linha.index[0].strftime('%Y-%m-%d')
volatilidade_hoje = ultima_linha['target_vol'].values[0]

# Mandamos o modelo prever o que vai acontecer daqui a 5 dias úteis!
previsao_futura_crua = model.predict(ultima_linha[features])[0]
previsao_futura = np.clip(previsao_futura_crua, 0.01, limite_maximo_vol)

print(f"\n===============================================")
print(f"A PREVISÃO DO FUTURO\n")
print(f"===============================================")
print(f"  Data Base (Último Pregão) : {data_base}")
print(f"  Volatilidade Atual        : {volatilidade_hoje*100:.1f}% a.a.")
print(f"  Previsão para daqui 5 dias: {previsao_futura*100:.1f}% a.a.")
print(f"  Margem de Flutuação       : [{max(0, previsao_futura - final_rmse)*100:.1f}%, {(previsao_futura + final_rmse)*100:.1f}%]")

tendencia = "ALTA 📈" if previsao_futura > volatilidade_hoje else "BAIXA 📉"
print(f"  Tendência Esperada        : {tendencia}")
print(f"===============================================\n")

# 7. GRÁFICOS: PREVISÃO E RESÍDUOS
fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(14, 10), gridspec_kw={'height_ratios': [2, 1]})

# Gráfico Superior (Previsões vs Realidade)
ax1.plot(y_test.index, y_test.values, label='Volatilidade Real', color='black', alpha=0.7)
ax1.plot(y_test.index, test_preds, label='LightGBM', color='blue', linestyle='--')
ax1.plot(y_test.index, baseline_preds, label='Baseline (Média 5d)', color='green', linestyle=':', alpha=0.6)
ax1.set_title(f'Backtest de Volatilidade (+5 dias) - {TICKER}')
ax1.legend()
ax1.grid(alpha=0.3)

# Gráfico Inferior (Resíduos/Erros - Foco nas crises)
residuos_lgbm = y_test.values - test_preds
residuos_baseline = y_test.values - baseline_preds

ax2.plot(y_test.index, residuos_lgbm, label='Erro LightGBM', color='blue', alpha=0.8)
ax2.plot(y_test.index, residuos_baseline, label='Erro Baseline', color='green', alpha=0.4, linestyle=':')
ax2.axhline(0, color='black', linestyle='-', linewidth=1.5)
ax2.set_title('Gráfico de Resíduos (Erro das previsões)')
ax2.legend()
ax2.grid(alpha=0.3)

plt.tight_layout()
plt.show()

# 8. Exportação do modelo

joblib.dump(model, 'lightgbm_model.joblib')
print("Modelo exportado com sucesso para 'lightgbm_model.joblib'!")